# -*- coding: utf-8 -*-
"""insightface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3RFzdoluretBF0IrdO05zwU3H9BBtjz
"""

# !pip install insightface onnxruntime

# from google.colab import drive
# drive.mount('/content/drive')

import os
import json
import numpy as np
from PIL import Image
import cv2
from insightface.app import FaceAnalysis

# Load InsightFace model
app = FaceAnalysis(name="buffalo_l")
app.prepare(ctx_id=0, det_size=(640, 640))  # ctx_id=0 GPU, ctx_id=-1 CPU

def get_embedding(image_path):
    img = cv2.imread(image_path)
    faces = app.get(img)

    if len(faces) == 0:
        return None

    # If multiple faces, take the largest one
    face = max(
        faces,
        key=lambda f: (f.bbox[2] - f.bbox[0]) * (f.bbox[3] - f.bbox[1])
    )

    emb = face.embedding
    emb = emb / np.linalg.norm(emb)
    return emb

# if torch.cuda.is_available():
#     device = torch.device("cuda")
# elif torch.backends.mps.is_available():
#     device = torch.device("mps")
# else:
#     device = torch.device("cpu")
# print(f"Using device: {device}")

def submit(results, groupname, url):
    res = {}
    res['groupname'] = groupname
    res['images'] = results
    res = json.dumps(res)
    # print(res)
    response = requests.post(url, res)
    try:
        result = json.loads(response.text)
        print(f"accuracy is {result['accuracy']}")
    except json.JSONDecodeError:
        print(f"ERROR: {response.text}")

data_folder = "/content/drive/MyDrive/competition/test"
query_folder = os.path.join(data_folder, "query")
gallery_folder = os.path.join(data_folder, "gallery")

query_images = []
query_filenames = []
gallery_images = []
gallery_filenames = []

for filename in os.listdir(query_folder):
    if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif')):
        img_path = os.path.join(query_folder, filename)
        query_filenames.append(filename)
        img = Image.open(img_path)
        query_images.append(img)

for filename in os.listdir(gallery_folder):
    if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif')):
        img_path = os.path.join(gallery_folder, filename)
        gallery_filenames.append(filename)
        img = Image.open(img_path)
        gallery_images.append(img)

# Print the number of images in each folder
print(f"Number of images in query folder: {len(query_images)}")
print(f"Number of images in gallery folder: {len(gallery_images)}")

print(len(query_filenames))

# Get faces from query images

query_features = []
valid_query_filenames = []
no_face_query = []

i=0
for filename in query_filenames:
    i+=1
    path = os.path.join(query_folder, filename)
    emb = get_embedding(path)

    if emb is not None:
        print(i, ". Added query")
        query_features.append(emb)
        valid_query_filenames.append(filename)
    else:
        print(i, ". No face found in query:", filename)
        no_face_query.append(filename)

query_features = np.vstack(query_features)

print(len(valid_query_filenames))

# Get faces from first 500 gallery images

no_face_gallery = []
gallery_features = []
valid_gallery_filenames = []

i=0
for filename in gallery_filenames[:500]:
    i+=1
    path = os.path.join(gallery_folder, filename)
    emb = get_embedding(path)

    if emb is not None:
        print(i, ". Added gallery")
        gallery_features.append(emb)
        valid_gallery_filenames.append(filename)
    else:
        print(i, ". No face found in gallery:", filename)
        no_face_gallery.append(filename)

# gallery_features = np.vstack(gallery_features)

# Get faces from first 500-1000 gallery images

# no_face_gallery = []
# gallery_features = []
# valid_gallery_filenames = []

i=500
for filename in gallery_filenames[500:1000]:
    i+=1
    path = os.path.join(gallery_folder, filename)
    emb = get_embedding(path)

    if emb is not None:
        print(i, ". Added gallery")
        gallery_features.append(emb)
        valid_gallery_filenames.append(filename)
    else:
        print(i, ". No face found in gallery:", filename)
        no_face_gallery.append(filename)

# gallery_features = np.vstack(gallery_features)

# Get faces from first 1000-1500 gallery images

# no_face_gallery = []
# gallery_features = []
# valid_gallery_filenames = []

i=1000
for filename in gallery_filenames[1000:1500]:
    i+=1
    path = os.path.join(gallery_folder, filename)
    emb = get_embedding(path)

    if emb is not None:
        print(i, ". Added gallery")
        gallery_features.append(emb)
        valid_gallery_filenames.append(filename)
    else:
        print(i, ". No face found in gallery:", filename)
        no_face_gallery.append(filename)

# gallery_features = np.vstack(gallery_features)

print(no_face_gallery[260:])

# Get faces from first 1500-2000 gallery images

# no_face_gallery = []
# gallery_features = []
# valid_gallery_filenames = []

i=1502
for filename in gallery_filenames[1502:2000]:
    i+=1
    path = os.path.join(gallery_folder, filename)
    emb = get_embedding(path)

    if emb is not None:
        print(i, ". Added gallery")
        gallery_features.append(emb)
        valid_gallery_filenames.append(filename)
    else:
        print(i, ". No face found in gallery:", filename)
        no_face_gallery.append(filename)

# gallery_features = np.vstack(gallery_features)

# Get faces from first 2000-2500 gallery images

# no_face_gallery = []
# gallery_features = []
# valid_gallery_filenames = []

i=2000
for filename in gallery_filenames[2000:2500]:
    i+=1
    path = os.path.join(gallery_folder, filename)
    emb = get_embedding(path)

    if emb is not None:
        print(i, ". Added gallery")
        gallery_features.append(emb)
        valid_gallery_filenames.append(filename)
    else:
        print(i, ". No face found in gallery:", filename)
        no_face_gallery.append(filename)

# gallery_features = np.vstack(gallery_features)

# Get faces from first 2500-3000 gallery images

# no_face_gallery = []
# gallery_features = []
# valid_gallery_filenames = []

i=2500
for filename in gallery_filenames[2500:]:
    i+=1
    path = os.path.join(gallery_folder, filename)
    emb = get_embedding(path)

    if emb is not None:
        print(i, ". Added gallery")
        gallery_features.append(emb)
        valid_gallery_filenames.append(filename)
    else:
        print(i, ". No face found in gallery:", filename)
        no_face_gallery.append(filename)

# gallery_features = np.vstack(gallery_features)

# print(len(valid_gallery_filenames))
gallery_features = np.vstack(gallery_features)

similarity_matrix = query_features @ gallery_features.T

top_k = min(10, len(valid_gallery_filenames))
top_k_indices = np.argsort(-similarity_matrix, axis=1)[:, :top_k]

results = {}

for i, query_filename in enumerate(valid_query_filenames):
    results[query_filename] = [
        valid_gallery_filenames[idx] for idx in top_k_indices[i]
    ]

for query_filename, matches in results.items():
    print(f"Top {top_k} matches for {query_filename}:")
    for j, gallery_filename in enumerate(matches):
        print(f"  {j+1}: {gallery_filename}")

max_len = 0
min_len = 10

for x in results:
  if len(results[x]) > max_len:
    max_len = len(results[x])
  if len(results[x]) < min_len:
    min_len = len(results[x])

print(max_len)
print(min_len)

print(len(results))
print(len(no_face_query))
# list(results.keys())[0]

import json

with open("results.json", "w") as f:
    json.dump(results, f, indent=2)



import torch
from torchvision.models import resnet50, ResNet50_Weights

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
print(f"Using device: {device}")

def batching_15(images, batch_size=32):
    features = []
    for i in range(0, len(images), batch_size):
        tmp_images = images[i:i+batch_size]
        inputs = torch.stack([preprocess(img.convert("RGB")) for img in tmp_images]).to(device)
        with torch.no_grad():
            tmp_features = model(inputs)
            features.append(tmp_features)
    return torch.cat(features, dim=0)

##########
weights = ResNet50_Weights.IMAGENET1K_V2
model = resnet50(weights=weights)
model.fc = torch.nn.Identity()  # use penultimate-layer features for retrieval
model = model.to(device)
preprocess = weights.transforms()
model.eval()

print(query_images)

print("Processing query images...")
query_features_15 = batching_15(query_images, batch_size=16)
print("Processing gallery images...")
gallery_features_15 = batching_15(gallery_images, batch_size=256)

# Normalize features
print("Normalizing features...")
query_features = torch.nn.functional.normalize(query_features, p=2, dim=1)
gallery_features = torch.nn.functional.normalize(gallery_features, p=2, dim=1)

print("Computing cosine similarity matrix...")
similarity_matrix = torch.matmul(query_features, gallery_features.T)

import matplotlib.pyplot as plt

def show_retrieval(query_filename, results, query_folder, gallery_folder, top_k=5):
    retrieved = results[query_filename][:top_k]

    plt.figure(figsize=(3 * (top_k + 1), 4))

    # Query image
    query_path = os.path.join(query_folder, query_filename)
    query_img = Image.open(query_path).convert("RGB")

    plt.subplot(1, top_k + 1, 1)
    plt.imshow(query_img)
    plt.title(f"QUERY\n{query_filename}", fontsize=10)
    plt.axis("off")

    # Retrieved gallery images
    for i, gallery_filename in enumerate(retrieved):
        gallery_path = os.path.join(gallery_folder, gallery_filename)
        gallery_img = Image.open(gallery_path).convert("RGB")

        plt.subplot(1, top_k + 1, i + 2)
        plt.imshow(gallery_img)
        plt.title(f"Rank {i+1}\n{gallery_filename}", fontsize=10)
        plt.axis("off")

    plt.tight_layout()
    plt.show()

show_retrieval(list(results.keys())[150], results, query_folder, gallery_folder, top_k=100)

for query_filename in list(results.keys())[0]:
    show_retrieval(query_filename, results, query_folder, gallery_folder, top_k=5)

import requests
# # Submit the results
# submit(results=results, groupname="CTK", url="http://videosim.disi.unitn.it:3001/retrieval/")